permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
  
# 作者信息
author: 
  name: Longhaier
  email: 1029418861@qq.com
  link: http://longhaier.cn
  weibo: http://weibo.com/orangeissweet
  github: https://github.com/Longhaier
  douban: https://www.douban.com/people/82189768/
  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: Longhaier的博客
description: My personal blog
url: http://longhaier.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/yellowdeer.jpg
favicon: /public/img/yellowdeer.jpg

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
