permalink: /:year/:month/:day/:title.html
paginate: 10


  
markdown:       kramdown
highlighter:    rouge
kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"
 #use_coderay:               true


# 作者信息
author: 
  name: Joe
  email: 1029418861@qq.com
  link: http://longhaier.cn
  weibo: http://weibo.com/3281054762/profile?rightmod=1&wvr=6&mod=personinfo
  github: https://github.com/Longhaier
  music: https://www.douban.com/people/82189768/
  linkedin: http://www.linkedin.com/in/%E6%B5%B7%E6%B6%9B-%E5%BC%A0-802019b5/

# 站点信息
title: Joe's blog
description: My personal blog
url: http://longhaier.cn
rss_url: /pages/atom.xml
baseurl: 

# gavatar头像及Favicon
gavatar: /public/img/picture.png
favicon: /public/img/picture.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: longhaier.cn

# disqus 设置
disqus:
  shortname: Joe

# 主题设置，自动激活某个标签
active: CS

# 首页除了最新文章外显示分类
cates: 
  - CS
  - Knowledge
  - Experience

# 中文本地化
locals:
  tags: tags
  about: about
  newest: newest
  archive: archive
